### ISSUE TITLE
Texto de la pagina

### ISSUE THREAD

**Issue by diegomartin010** [gauchoGS/gauchogs.github.io#3]
- Verificar y corregir cualquier error ortográfico, de concepto, mensajes, etc. Que este presente en toda la pagina web, en cualquiera de los html, formularios, mensajes, secciones, menús.

- Pensar , agregar o modificar en a la pagina las descripciones de los servicios que vamos a brindar. Determinar si son acordes a lo que se pretende realmente brindar a los clientes.

- Mejorar las frases y las descripciones de los integrantes del equipo.

- Determinar si la distribución de colores de las paginas es realmente la deseada.

**Comment by ColoLP** [comment]
Resueltos errores ortograficos, agregado de acentuaciones.

Las descripciones son considerablemente buenas, son consisas y bien al pie de lo que se hace. 

Cambiada las frases, si hay alguna ocurrencia diferente la cambio. 

La distribucion de colores es buena. No esta muy sobrecargada. 

Ahora bien, creeria que en el incio se podria agregar todas las secciones en vez de HTML's separados.
