### ISSUE TITLE
Background Index 

### ISSUE THREAD

**Issue by diegomartin010** [gauchoGS/gauchogs.github.io#6]
Determinar si el fondo negro en la pagina de index va bien, o si deberíamos ponerle otro color de fondo, o cargar alguna imagen (ej. Un mate, en color oscuro, o que se yo).

![cacawd](https://user-images.githubusercontent.com/9575268/31058877-cb3516c8-a6d1-11e7-8199-8d3830e23c45.JPG)

**Comment by ColoLP** [comment]
Considero que el fondo que tiene actualmente es correcto. 
En cuanto al logo, si vamos a realizar otros servicios no le dejaria el "Game Studio" debajo del logo. 
Ya que no seria un estudio solo de desarrollo de videojuegos.
