### ISSUE TITLE
Icono Header

### ISSUE THREAD

**Issue by diegomartin010** [gauchoGS/gauchogs.github.io#7]
Buscar un icono para que aparezca en las pestañas del sitio en el navegador. Pensar algo representativo: 
- Un mate,
- una G,
- una estrella de david, no se ...

![captura](https://user-images.githubusercontent.com/9575268/31078768-c2d3a41c-a759-11e7-8a04-bf43412e2aad.JPG)

**Comment by ColoLP** [comment]
Listo. Ya se encuentra el mate como icono de las pestañas.
