### ISSUE TITLE
Verificar Responsividad

### ISSUE THREAD

**Issue by diegomartin010** [gauchoGS/gauchogs.github.io#9]
Desde el celular se ve medio chanfleado. No es que sea gran cosa, pero si alguien ingresa desde un celular no se ve muy profesional.
Igualmente capaz que solo sucede con mi browser .. 

![whatsapp image 2017-10-02 at 13 01 47 1](https://user-images.githubusercontent.com/9575268/31087027-e8cd94d0-a771-11e7-8650-d84d045336fb.jpeg)

**Comment by ColoLP** [comment]
Es tema, de responsividad de mi celu se ve igual que el tuyo.

**Comment by jmg93** [comment]
Si, se ve mal pero creo que se como se soluciona.
En un rato lo veo
